Travtus/.github

- .github/workflows/build_and_deploy_sam_template_one_environment.yaml
Fixup wording in the specific environment CI/CD workflow.
> Fixup wording in build_and_deploy_sam_template_one_environment.yaml

- .github/workflows/build_and_deploy_sam_template.yaml
- .github/workflows/build_and_deploy_sam_template_one_environment.yaml
This PR fixes a bug with the CI/CD templates whereby the deployment did not include the requirements.
Build is now a part of each individual job before deployment
> Bugfix: Sam build requirements not included

- .github/workflows/create_main_release.yaml
- .github/workflows/get_new_tag.py
Add a new workflow that creates a new release for a main branch.
This workflow will only work for repos where releases are tagged following the v{major}.{minor}.{patch} pattern.
> Add a workflow for creating a release from a main branch

- .github/workflows/install_and_zip_and_upload_to_s3.yaml
- .github/workflows/upload_to_s3.yaml
- .github/workflows/zip_and_upload_to_s3.yaml
Because some services require persisting artifacts in S3, this PR adds two new workflows to facilitate this. One workflow uploads to an S3 bucket, and the other zips and then uploads to an S3 bucket.
> Add upload to s3, and zip and upload to s3 workflows

- .github/workflows/run_behave_tests.yaml
In this PR we add a workflow for running a PR check with behave BDD tests.
> Add bdd workflow

- .github/workflows/starter_template.yaml
- pyproject.toml
Add mypy and ruff checks in CI pipeline
> Enable mypy and ruff

- .github/workflows/starter_template.yaml
- pyproject.toml
Add coverage test step to CI pipeline. Be default, codes in  `*/interfaces/*`, `*/config*.py`, we will increase it time by time.
> feat: add test coverage step

- .github/workflows/checkov_scan.yaml
- .github/workflows/starter_template.yaml
Add a usable workflow for running a checkov IaC scan, which will spot infrastructure that is non-compliat with SOC2.
Add the same scan to the starter template, where it can also be ran from.
{ REPLACE ALL TEXT IN CURLY BRACES }
{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related Notion tasks. This section will be automatically compiled into the release notes, so please:
- describe the impact of the change in this PR to the *user* of this repository (e.g. end user, contributor, developer).
- describe the new product behaviour in *present tense*, and the old behaviour and how it's been changed in *past tense*.
- Use the *Royal We*: *"We"* made changes, not *"I"* made …
> Add a checkov IaC scan workflow and step to starter template

- .github/workflows/build_and_deploy_integration_test_template.yaml
we are making changes to add in integration Tests actions template to use in other services. to create a seperate stack then run the process and terminate the stack
> integration Tests actions template

- .github/workflows/starter_template.yaml
> feat: add django test to CI pipeline

- .github/workflows/build_and_deploy_integration_test_template.yaml
> Integration Testing github actions changes

- .github/workflows/build_and_deploy_integration_test_template.yaml
bugfix to commit only a required file, instead of the entire folder.
> bugfix to commit only a required file,

- .github/workflows/build_and_deploy_integration_test_template.yaml
- .github/workflows/build_and_deploy_sam_template.yaml
- .github/workflows/build_and_deploy_sam_template_one_environment.yaml
> support to multi arch builds to enable ARM runtimes

- .github/workflows/starter_template.yaml
> Provide an option to enable imports checks, default to true

- .github/workflows/starter_template.yaml
support for enabling postgres db as a service container when testing db connection during uni testing.
> support for enabling postgres db

- .github/workflows/build_and_deploy_sam_template.yaml
> feat: validate with template path

- .github/workflows/build_and_deploy_sam_template.yaml
- .github/workflows/build_and_deploy_sam_template_one_environment.yaml
as title. we inject github token from workflows so we can use it in cloudformation template.
> feat: inject github token into cloudformation

- .github/workflows/build_and_deploy_sam_template.yaml
> refactor: inject github token to sam

- .github/workflows/starter_template.yaml
> support for skipping few Checkov scan Tests

- .github/workflows/uv_pull_request_checks.yaml
- README.md
- pyproject-uv.toml
> Add reusable workflow for uv environment

- .github/workflows/build_and_deploy_sam_template_one_environment.yaml
To resolve this issue: https://github.com/aws/aws-sam-cli/issues/8139
> Ping sam version
